name: Build and deploy React App to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build
      
      - name: Deploy
        run: |
          git config user.name 'Shadin Hussein'
          git config user.email 'shadin.hussein@gmail.com'
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy